version: '3'
services:
  awscdkec:
    env_file:
    - aws.env
    build:
      context: .
      dockerfile: Dockerfile
    image: node:14.18.2-buster-slim
    container_name: awscdkec
    volumes:
      - ./data/:/root/data
      - /root/data/hello-cdkec/node_modules
      - ./pems/:/root/.aws/pems
      - ./aws/:/root/.aws
    network_mode: bridge
